server:
  port: 8081

spring:  datasource:    url: jdbc:mysql://localhost:3306/mongo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root